main: me.IcyFlameX.GTACops.main.Main
author: IcyFlameX
name: GTACops
version: "2.3.1"
api-version: "1.13"
softdepend: [PlaceholderAPI]
commands:
  gcops:
    description: Shows information regarding GTACops plugin
    usage: /<command>